apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
data:
  my.cnf: |-
    [client]
    port                                            = 3306
    #socket                                          = /tmp/mysql.sock
    
    
    [mysqld]
    ##### Default
    user                                            = ntuple
    port                                            = 3306
    socket                                          = /var/run/mysqld/mysqld.sock
    #basedir                                         = /home/ntuple/server/mysql
    #datadir                                         = /data/db_data
    #tmpdir                                          = /tmp
    default-storage-engine                          = innodb
    event_scheduler                                 = 0
    lower_case_table_names                          = 0
    performance_schema                              = 1
    default_authentication_plugin                   = mysql_native_password
    #transaction_isolation                           = READ-COMMITTED
    #sql_mode                                        = NO_ENGINE_SUBSTITUTION
    
    skip-external-locking
    skip-name-resolve
    skip-host-cache
    
    
    ##### Character
    character-set-filesystem                        = utf8
    character-set-server                            = utf8mb4
    collation_server                                = utf8mb4_general_ci
    
    
    ##### Connection
    max_connections                                 = 2000
    max_connect_errors                              = 9999
    max_allowed_packet                              = 512M
    wait_timeout                                    = 300
    interactive-timeout                             = 300
    back_log = 2000
    
    ##### Thread pool (ON)
    #thread_pool_size                                = 64
    #thread_pool_max_threads                         = 65536
    #thread_handling                                 = pool-of-threads
    
    # Common Config
    binlog_cache_size = 1M
    join_buffer_size = 256K
    interactive_timeout = 300
    max_heap_table_size = 1G
    tmp_table_size = 1G
    read_buffer_size = 128K
    read_rnd_buffer_size = 128K
    sort_buffer_size = 512K
    table_open_cache = 20000
    open_files_limit = 65536
    thread_cache_size = 1000
    optimizer_search_depth = 12
    thread_stack = 256K
    group_concat_max_len = 1000000
    
    
    # Query Cache Disable
    #query_cache_type = 0
    
    
    ##### Engine
    ## Innodb config
    innodb_buffer_pool_size = 2G
    innodb_buffer_pool_instances = 8
    innodb_file_per_table = 1
    innodb_flush_method = O_DIRECT
    innodb_lock_wait_timeout = 40
    innodb_log_buffer_size = 32M
    innodb_thread_sleep_delay = 0
    innodb_fast_shutdown = 1
    innodb_thread_concurrency = 0
    innodb_read_io_threads = 8
    innodb_write_io_threads = 8
    innodb_open_files = 65536
    innodb_flush_log_at_trx_commit = 0
    innodb_sort_buffer_size = 64M
    innodb_online_alter_log_max_size = 2G
    
    #innodb_log_file_size = 1G
    #innodb_log_group_home_dir = /data/innodb_log
    #innodb_log_files_in_group = 3
    
    innodb_data_file_path = ibdata1:1G;ibdata2:1G;ibdata3:1G:autoextend
    #innodb_data_home_dir = /data/innodb_log
    
    innodb_undo_tablespaces = 3
    #innodb_undo_directory = /data/innodb_log
    
    
    
    ### Aria Storage
    #aria_pagecache_buffer_size                      = 128M
    
    
    # Fulltext Variables
    innodb_ft_min_token_size                        = 2
    
    
    ## MyISAM Config
    bulk_insert_buffer_size = 64M
    key_buffer_size = 64K
    myisam_max_sort_file_size = 1G
    # myisam_repair_threads = 1
    myisam_sort_buffer_size = 64M
    
    
    ##### Log Write
    ### Slow Query
    #slow_query_log                                  = 1
    #slow_query_log_file                             = /log/etc_log/ntuple01_slow.log
    #long_query_time                                 = 3
    
    
    ### Error
    #log-error                                       = /log/etc_log/ntuple01_error.log
    #log_warnings                                    = 1
    
    ##### Replication
    #server-id                                       = 1
    #expire_logs_days                                = 1
    #log-bin                                         = /log/binary_log/ntuple01-bin
    #binlog_format                                   = row
    #max_binlog_size                                 = 1G
    #log_bin_trust_function_creators                 = 1
    
    #gtid-mode=ON
    #enforce-gtid-consistency=ON
    #log_slave_updates=ON
    #binlog-format = row
    #binlog_commit_wait_usec = 5000
    #binlog_commit_wait_count = 50
    
    
    #### Slave Options
    # relay_log                                      = /log/binary_log/01-relay
    # read_only                                      = 1
    # slave_parallel_threads = 10
    
    
    [mysql]
    no-auto-rehash
    
    [mysqldump]
    quick
    
    [mysqlhotcopy]
    interactive-timeout                             = 300
    
    [mysqld_safe]
    open_files_limit                                = 8192
